/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import { globalStyles } from "styles/globalstyles";
import { Navbar } from "components";

export const PageWrapper = (props: any) => {
    const { children } = props;
    globalStyles();
    return (
        <>
            <Head>
                <title>Frontend Mentor | Planets fact site</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                ></meta>
                <link rel="icon" href="assets/favicon-32x32.png" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Antonio:wght@500&family=Spartan:wght@400;700&display=swap"
                    rel="stylesheet"
                    crossOrigin=""
                />
            </Head>
            <Navbar />
            {children}
        </>
    );
};
